version: '2'
services:
    advmanagementsystem-app:
        image: advmanagementsystem
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://advmanagementsystem-mysql:3306/advmanagementsystem?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    advmanagementsystem-mysql:
        extends:
            file: mysql.yml
            service: advmanagementsystem-mysql
